import type { Release } from "../types.js"

/** El seed describe la ficha; visibilidad y marcas de venta las pone `seed()`. */
export type SeedRelease = Omit<Release, "visible" | "isPreorder" | "isFeatured">

/**
 * Catálogo inicial con el que se siembra la base la primera vez.
 * Artistas, títulos, sellos y precios son inventados: reemplazar por el catálogo real.
 */
export const SEED_RELEASES: SeedRelease[] = [
  {
    id: "trepidacion-suburbio-norte",
    artist: "Trepidación",
    title: "Suburbio Norte",
    year: 2025,
    genre: "Rock",
    label: "Cinta Muerta",
    format: "LP",
    condition: "Nuevo",
    price: 27990,
    stock: 6,
    isNew: true,
    tracklist: [
      { position: "A1", title: "Suburbio norte", duration: "4:12" },
      { position: "A2", title: "Cable a tierra", duration: "3:38" },
      { position: "B1", title: "Turno de noche", duration: "5:02" },
      { position: "B2", title: "La última micro", duration: "6:24" },
    ],
  },
  {
    id: "orquesta-fantasma-humo-lento",
    artist: "Orquesta Fantasma",
    title: "Humo Lento",
    year: 2024,
    genre: "Jazz",
    label: "Sello Austral",
    format: "2LP",
    condition: "Nuevo",
    price: 42990,
    stock: 3,
    isNew: true,
    tracklist: [
      { position: "A1", title: "Humo lento", duration: "8:41" },
      { position: "B1", title: "Contraluz", duration: "6:15" },
      { position: "C1", title: "Sesión de las tres", duration: "9:03" },
      { position: "D1", title: "Coda para vientos", duration: "5:47" },
    ],
  },
  {
    id: "maquina-de-agua-planta-baja",
    artist: "Máquina de Agua",
    title: "Planta Baja",
    year: 2026,
    genre: "Electrónica",
    label: "Corriente Continua",
    format: "LP",
    condition: "Nuevo",
    price: 31990,
    stock: 11,
    isNew: true,
    tracklist: [
      { position: "A1", title: "Planta baja", duration: "6:30" },
      { position: "A2", title: "Sala de máquinas", duration: "5:12" },
      { position: "B1", title: "Condensación", duration: "7:44" },
      { position: "B2", title: "Salida de emergencia", duration: "4:58" },
    ],
  },
  {
    id: "violeta-industrial-cordillera-adentro",
    artist: "Violeta Industrial",
    title: "Cordillera Adentro",
    year: 2023,
    genre: "Latinoamericana",
    label: "Sello Austral",
    format: "LP",
    condition: "Nuevo",
    price: 25990,
    stock: 0,
    isNew: false,
    tracklist: [
      { position: "A1", title: "Cordillera adentro", duration: "3:52" },
      { position: "A2", title: "Camino de tierra", duration: "4:26" },
      { position: "B1", title: "Río claro", duration: "5:19" },
      { position: "B2", title: "Vuelta al valle", duration: "4:03" },
    ],
  },
  {
    id: "delta-8-terciopelo-quemado",
    artist: "Delta 8",
    title: "Terciopelo Quemado",
    year: 2022,
    genre: "Soul",
    label: "Cinta Muerta",
    format: "LP",
    condition: "Usado",
    price: 18990,
    stock: 2,
    isNew: false,
    tracklist: [
      { position: "A1", title: "Terciopelo quemado", duration: "4:44" },
      { position: "A2", title: "Nada que probar", duration: "3:31" },
      { position: "B1", title: "Segundo piso", duration: "5:56" },
      { position: "B2", title: "Se apagan las luces", duration: "4:17" },
    ],
  },
  {
    id: "atlas-menor-banda-sonora",
    artist: "Atlas Menor",
    title: "Banda Sonora Original",
    year: 2025,
    genre: "Bandas sonoras",
    label: "Archivo 33",
    format: "2LP",
    condition: "Nuevo",
    price: 45990,
    stock: 4,
    isNew: true,
    tracklist: [
      { position: "A1", title: "Tema principal", duration: "3:08" },
      { position: "B1", title: "Persecución en el puerto", duration: "4:52" },
      { position: "C1", title: "Interludio", duration: "2:34" },
      { position: "D1", title: "Créditos finales", duration: "6:41" },
    ],
  },
  {
    id: "los-cables-alta-tension",
    artist: "Los Cables",
    title: "Alta Tensión",
    year: 2021,
    genre: "Rock",
    label: "Corriente Continua",
    format: "LP",
    condition: "Usado",
    price: 16990,
    stock: 5,
    isNew: false,
    tracklist: [
      { position: "A1", title: "Alta tensión", duration: "3:22" },
      { position: "A2", title: "Fusible", duration: "2:58" },
      { position: "B1", title: "Corte de luz", duration: "4:36" },
      { position: "B2", title: "Generador", duration: "5:11" },
    ],
  },
  {
    id: "nube-baja-sesiones-de-invierno",
    artist: "Nube Baja",
    title: "Sesiones de Invierno",
    year: 2024,
    genre: "Jazz",
    label: "Archivo 33",
    format: "EP",
    condition: "Nuevo",
    price: 19990,
    stock: 8,
    isNew: false,
    tracklist: [
      { position: "A1", title: "Primera sesión", duration: "7:20" },
      { position: "B1", title: "Segunda sesión", duration: "8:05" },
    ],
  },
  {
    id: "radio-pacifico-onda-corta",
    artist: "Radio Pacífico",
    title: "Onda Corta",
    year: 2026,
    genre: "Electrónica",
    label: "Corriente Continua",
    format: '7"',
    condition: "Nuevo",
    price: 12990,
    stock: 14,
    isNew: true,
    tracklist: [
      { position: "A", title: "Onda corta", duration: "3:45" },
      { position: "B", title: "Onda corta (versión dub)", duration: "4:12" },
    ],
  },
  {
    id: "ceniza-fina-domingo-largo",
    artist: "Ceniza Fina",
    title: "Domingo Largo",
    year: 2023,
    genre: "Latinoamericana",
    label: "Sello Austral",
    format: "LP",
    condition: "Nuevo",
    price: 24990,
    stock: 7,
    isNew: false,
    tracklist: [
      { position: "A1", title: "Domingo largo", duration: "4:55" },
      { position: "A2", title: "Patio interior", duration: "3:47" },
      { position: "B1", title: "Sombra corta", duration: "5:33" },
      { position: "B2", title: "Se hizo tarde", duration: "4:09" },
    ],
  },
  {
    id: "hermanas-eco-caja-1971-1979",
    artist: "Hermanas Eco",
    title: "Caja 1971–1979",
    year: 2025,
    genre: "Soul",
    label: "Archivo 33",
    format: "Box",
    condition: "Nuevo",
    price: 89990,
    stock: 1,
    isNew: true,
    tracklist: [
      { position: "A1", title: "Primer sencillo", duration: "3:14" },
      { position: "B1", title: "Grabaciones de casa", duration: "4:28" },
      { position: "C1", title: "En vivo, 1975", duration: "6:52" },
      { position: "D1", title: "Descartes", duration: "5:36" },
    ],
  },
  {
    id: "turno-noche-marea-roja",
    artist: "Turno Noche",
    title: "Marea Roja",
    year: 2022,
    genre: "Rock",
    label: "Cinta Muerta",
    format: "LP",
    condition: "Usado",
    price: 15990,
    stock: 3,
    isNew: false,
    tracklist: [
      { position: "A1", title: "Marea roja", duration: "4:31" },
      { position: "A2", title: "Costa afuera", duration: "3:56" },
      { position: "B1", title: "Bajamar", duration: "6:08" },
      { position: "B2", title: "Faro", duration: "5:22" },
    ],
  },
]
